# Generated by Django 5.1.3 on 2024-12-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_categories',
            field=models.CharField(choices=[('спорт', 'news'), ('политика', 'article'), ('образование', 'studing'), ('финансы', 'finance')], default='образование', max_length=11),
        ),
        migrations.AlterField(
            model_name='comment',
            name='current_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.post'),
        ),
    ]
