# Generated by Django 4.2.11 on 2025-02-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_categories_en_us',
            field=models.CharField(choices=[('спорт', 'sport'), ('политика', 'politic'), ('образование', 'studying'), ('финансы', 'finance')], default='образование', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_categories_ru',
            field=models.CharField(choices=[('спорт', 'sport'), ('политика', 'politic'), ('образование', 'studying'), ('финансы', 'finance')], default='образование', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_en_us',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок'),
        ),
    ]
