# Generated by Django 4.2.11 on 2025-02-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_name_categories_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_categories_en_us',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_categories_ru',
        ),
    ]
