# Generated by Django 5.1.3 on 2024-12-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_name_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_categories',
            field=models.CharField(choices=[('спорт', 'sport'), ('политика', 'politic'), ('образование', 'studying'), ('финансы', 'finance')], default='образование', max_length=11),
        ),
        migrations.AlterField(
            model_name='post',
            name='choice_categories',
            field=models.CharField(choices=[('новость', 'news'), ('статья', 'article')], default='news', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок'),
        ),
    ]
