# Generated by Django 4.2.11 on 2025-02-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_category_name_categories_en_us_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorytransleteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='name_categories_en_us',
            field=models.CharField(choices=[('sport', 'sport'), ('politic', 'politic'), ('studying', 'studying'), ('finance', 'finance')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_categories_ru',
            field=models.CharField(choices=[('sport', 'sport'), ('politic', 'politic'), ('studying', 'studying'), ('finance', 'finance')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_categories',
            field=models.CharField(choices=[('sport', 'sport'), ('politic', 'politic'), ('studying', 'studying'), ('finance', 'finance')], max_length=11),
        ),
        migrations.AlterField(
            model_name='post',
            name='choice_categories',
            field=models.CharField(choices=[('новость', 'news'), ('статья', 'article')], default='новость', max_length=7),
        ),
    ]
